name: Update Gallery

on:
  workflow_dispatch:


jobs:
  generate-videos:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        sudo apt install ffmpeg
        python -m pip install --upgrade pip
        pip install setuptools numpy matplotlib opencv-python
        pip install git+https://github.com/tum-pbs/pbdl-dataset@develop

    - name: Fetch index
      run: python scripts/fetch_index.py

    - name: Load datasets and create videos
      run: python scripts/create_videos.py

    - name: Upload generated videos and index
      uses: actions/upload-artifact@v4
      with:
        name: generated-content
        path: public/  # Change this to the directory containing the generated content

  deploy-gallery:
    runs-on: ubuntu-latest
    needs: generate-videos

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Download generated content
      uses: actions/download-artifact@v4
      with:
        name: generated-content
        path: public/  # Change this to the desired download directory

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change this to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build  # Change this to your build command

    - name: List build output
      run: ls -R ./build  # Change this to your build output directory

    - name: Commit and push videos
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'Sebastian Pfister'
        git config --global user.email 'sebastian.pfister@tum.de'
        git status
        git add public/
        if ! git diff-index --quiet HEAD --; then
          git commit -am 'added preview videos (automated)'
          git push https://$GH_PAT@github.com/pfistse/dataset-gallery.git HEAD:main
        else
          echo "No changes to commit"

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Change this to your build output directory
        publish_branch: gh-pages  # Change this to your GitHub Pages branch